import type { SvelteComponentTyped } from 'svelte' 
export class AcademicCap extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Adjustments extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Annotation extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Archive extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowCircleDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowCircleLeft extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowCircleRight extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowCircleUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowLeft extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowNarrowDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowNarrowLeft extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowNarrowRight extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowNarrowUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowRight extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ArrowsExpand extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class AtSymbol extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Backspace extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class BadgeCheck extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Ban extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Beaker extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Bell extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class BookOpen extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class BookmarkAlt extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Bookmark extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Briefcase extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Cake extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Calculator extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Calendar extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Camera extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Cash extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChartBar extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChartPie extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChartSquareBar extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChatAlt2 extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChatAlt extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Chat extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CheckCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Check extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronDoubleDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronDoubleLeft extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronDoubleRight extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronDoubleUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronLeft extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronRight extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ChevronUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Chip extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ClipboardCheck extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ClipboardCopy extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ClipboardList extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Clipboard extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Clock extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CloudDownload extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CloudUpload extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Cloud extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Code extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Cog extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Collection extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ColorSwatch extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CreditCard extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CubeTransparent extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Cube extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CurrencyBangladeshi extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CurrencyDollar extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CurrencyEuro extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CurrencyPound extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CurrencyRupee extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CurrencyYen extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class CursorClick extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Database extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DesktopComputer extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DeviceMobile extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DeviceTablet extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentAdd extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentDownload extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentDuplicate extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentRemove extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentReport extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentSearch extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DocumentText extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Document extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DotsCircleHorizontal extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DotsHorizontal extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class DotsVertical extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Download extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Duplicate extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class EmojiHappy extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class EmojiSad extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ExclamationCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Exclamation extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ExternalLink extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class EyeOff extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Eye extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class FastForward extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Film extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Filter extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class FingerPrint extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Fire extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Flag extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class FolderAdd extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class FolderDownload extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class FolderOpen extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class FolderRemove extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Folder extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Gift extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class GlobeAlt extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Globe extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Hand extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Hashtag extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Heart extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Home extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Identification extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class InboxIn extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Inbox extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class InformationCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Key extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Library extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class LightBulb extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class LightningBolt extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Link extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class LocationMarker extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class LockClosed extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class LockOpen extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Login extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Logout extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MailOpen extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Mail extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Map extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MenuAlt1 extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MenuAlt2 extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MenuAlt3 extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MenuAlt4 extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Menu extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Microphone extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MinusCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MinusSm extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Minus extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Moon extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class MusicNote extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Newspaper extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class OfficeBuilding extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PaperAirplane extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PaperClip extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Pause extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PencilAlt extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Pencil extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PhoneIncoming extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PhoneMissedCall extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PhoneOutgoing extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Phone extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Photograph extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Play extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PlusCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PlusSm extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Plus extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PresentationChartBar extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class PresentationChartLine extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Printer extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Puzzle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Qrcode extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class QuestionMarkCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ReceiptRefund extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ReceiptTax extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Refresh extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Reply extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Rewind extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Rss extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class SaveAs extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Save extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Scale extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Scissors extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class SearchCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Search extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Selector extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Server extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Share extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ShieldCheck extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ShieldExclamation extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ShoppingBag extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ShoppingCart extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class SortAscending extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class SortDescending extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Sparkles extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Speakerphone extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Star extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class StatusOffline extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class StatusOnline extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Stop extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Sun extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Support extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class SwitchHorizontal extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class SwitchVertical extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Table extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Tag extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Template extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Terminal extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ThumbDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ThumbUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Ticket extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Translate extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Trash extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class TrendingDown extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class TrendingUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Truck extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Upload extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class UserAdd extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class UserCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class UserGroup extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class UserRemove extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class User extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Users extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Variable extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class VideoCamera extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ViewBoards extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ViewGridAdd extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ViewGrid extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ViewList extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class VolumeOff extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class VolumeUp extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class Wifi extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class XCircle extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class X extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ZoomIn extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
export class ZoomOut extends SvelteComponentTyped<{size?: string,solid?: boolean, class?:string}> {}
